import Head from "next/head";

export default function Layout({ children }) {
    return (
        <>
            <Head>
                <title>Adventures</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/world-map.ico" />
            </Head>
            <main>{children}</main>
        </>
    );
}